"""add routine block/pinned and workout exercise_order

Revision ID: 02c102e829b3
Revises: b256c6b23744
Create Date: 2026-09-28 09:18:51.613166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c102e829b3'
down_revision = 'b256c6b23744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('pinned', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_order', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('exercise_order')

    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_column('pinned')
        batch_op.drop_column('block')

    # ### end Alembic commands ###
