"""add stagnation_threshold to user

Revision ID: 09699c271fdd
Revises: 635287c10465
Create Date: 2026-07-23 19:06:20.086818

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "09699c271fdd"
down_revision = "635287c10465"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "stagnation_threshold",
                sa.Integer(),
                nullable=False,
                server_default="3",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("stagnation_threshold")

    # ### end Alembic commands ###
