"""add default rest seconds

Revision ID: 0c74af5bce91
Revises: 3a0c8a9893e3
Create Date: 2026-07-27 12:07:44.202678

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0c74af5bce91"
down_revision = "3a0c8a9893e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exercise_note", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("default_rest_seconds", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exercise_note", schema=None) as batch_op:
        batch_op.drop_column("default_rest_seconds")

    # ### end Alembic commands ###
