"""add_weekly_goal_history

Revision ID: 1776b45d5e23
Revises: e9f4eebdde96
Create Date: 2026-08-18 12:24:16.477906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1776b45d5e23'
down_revision = 'e9f4eebdde96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_goal_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_goal_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_goal_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_goal_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_goal_history_user_id'))

    op.drop_table('weekly_goal_history')
    # ### end Alembic commands ###
