"""rename performance_note to performance_rating

Revision ID: 1e00be185f4f
Revises: c54af52f188e
Create Date: 2026-07-24 12:25:38.977129

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1e00be185f4f"
down_revision = "c54af52f188e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("performance_rating", sa.Integer(), nullable=True)
        )
        batch_op.drop_column("performance_note")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("performance_note", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.drop_column("performance_rating")

    # ### end Alembic commands ###
