"""add rpe, make rir optional

Revision ID: 23200aa375a3
Revises: fa0b34d2e282
Create Date: 2026-07-21 14:37:23.488997

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "23200aa375a3"
down_revision = "fa0b34d2e282"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("set_entry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rpe", sa.Integer(), nullable=True))
        batch_op.alter_column("rir", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("set_entry", schema=None) as batch_op:
        batch_op.alter_column("rir", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("rpe")

    # ### end Alembic commands ###
