"""add exercise catalog

Revision ID: 2c24b08c00cb
Revises: 8b5979ae8267
Create Date: 2026-08-15 11:53:50.702783

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "2c24b08c00cb"
down_revision = "8b5979ae8267"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("primary_muscles", sa.String(length=255), nullable=True),
        sa.Column("equipment", sa.String(length=64), nullable=True),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("exercise", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_exercise_name"), ["name"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exercise", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exercise_name"))

    op.drop_table("exercise")
    # ### end Alembic commands ###
