"""add performance_comment

Revision ID: 2c8f9b588337
Revises: 1e00be185f4f
Create Date: 2026-07-24 12:40:32.161137

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "2c8f9b588337"
down_revision = "1e00be185f4f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("performance_comment", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.drop_column("performance_comment")

    # ### end Alembic commands ###
