"""add routines

Revision ID: 3a0c8a9893e3
Revises: 7701a8b5b550
Create Date: 2026-07-25 18:02:57.266231

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3a0c8a9893e3"
down_revision = "7701a8b5b550"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.add_column(sa.Column("routine_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_workout_routine_id"), ["routine_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_workout_routine_id", "routine", ["routine_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.drop_constraint("fk_workout_routine_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_workout_routine_id"))
        batch_op.drop_column("routine_id")

    # ### end Alembic commands ###
