"""body phase

Revision ID: 41238366774a
Revises: c33ff7099854
Create Date: 2026-10-04 18:23:59.042581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41238366774a'
down_revision = 'c33ff7099854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_phase', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('body_phase')

    # ### end Alembic commands ###
