"""training days and visit language

Revision ID: 48df2c79e0ac
Revises: 595c09482ca9
Create Date: 2026-10-02 10:22:35.665924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48df2c79e0ac'
down_revision = '595c09482ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=8), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_days', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('training_days')

    with op.batch_alter_table('landing_event', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
