"""routine sets range

Revision ID: 4ad17256d127
Revises: cfc8bba3958e
Create Date: 2026-10-03 16:42:17.515083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad17256d127'
down_revision = 'cfc8bba3958e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_sets_max', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_exercise', schema=None) as batch_op:
        batch_op.drop_column('target_sets_max')

    # ### end Alembic commands ###
