"""add completed to set_entry

Revision ID: 4b1a98fe2152
Revises: c304899f62c1
Create Date: 2026-08-16 14:30:36.309057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1a98fe2152'
down_revision = 'c304899f62c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_entry', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
