"""import draft

Revision ID: 4f57d3bf9fc9
Revises: 1dd195391b32
Create Date: 2026-10-05 13:58:42.719831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f57d3bf9fc9'
down_revision = '1dd195391b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_draft', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_draft_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_draft', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_draft_user_id'))

    op.drop_table('import_draft')
    # ### end Alembic commands ###
