"""personal basics

Revision ID: 5832103828ac
Revises: 4ad17256d127
Create Date: 2026-10-04 17:18:47.167192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5832103828ac'
down_revision = '4ad17256d127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_basic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise', name='uq_personal_basic_user_exercise')
    )
    with op.batch_alter_table('personal_basic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_basic_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal_basic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_basic_user_id'))

    op.drop_table('personal_basic')
    # ### end Alembic commands ###
