"""set completed_at

Revision ID: 595c09482ca9
Revises: bc5d1f511823
Create Date: 2026-10-01 17:04:06.043190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595c09482ca9'
down_revision = 'bc5d1f511823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_entry', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
