"""friends and athlete card

Revision ID: 5e68f3ab975a
Revises: 41238366774a
Create Date: 2026-10-04 18:59:59.853416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e68f3ab975a'
down_revision = '41238366774a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athlete_card',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('in_rankings', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('show_rank', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('show_level', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('show_streak', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('show_consistency', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('show_kg', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('show_bodyweight', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('featured_lifts', sa.Text(), server_default='[]', nullable=False),
    sa.Column('featured_achievements', sa.Text(), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('friendship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friendship_pair')
    )
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friendship_addressee_id'), ['addressee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendship_requester_id'), ['requester_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('friend_code', sa.String(length=12), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_friend_code'), ['friend_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_friend_code'))
        batch_op.drop_column('friend_code')

    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendship_requester_id'))
        batch_op.drop_index(batch_op.f('ix_friendship_addressee_id'))

    op.drop_table('friendship')
    op.drop_table('athlete_card')
    # ### end Alembic commands ###
