"""add effort_scale to workout

Revision ID: 635287c10465
Revises: 23200aa375a3
Create Date: 2026-07-21 22:16:34.141289

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "635287c10465"
down_revision = "23200aa375a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("effort_scale", sa.String(length=3), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.drop_column("effort_scale")

    # ### end Alembic commands ###
