"""daily activity usage counter (contador de uso por día, ver app/usage.py)

Revision ID: 6d559731c646
Revises: 6e5648d35b11
Create Date: 2026-10-02 17:14:30.877928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d559731c646'
down_revision = '6e5648d35b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('opened', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('planned_rest', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('css_retries', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_daily_activity_user_day')
    )
    with op.batch_alter_table('daily_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_activity_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_activity_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_activity_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_activity_day'))

    op.drop_table('daily_activity')
    # ### end Alembic commands ###
