"""landing stats: user agent, signup date and method

Revision ID: 6e289115dd5b
Revises: a4fd69e13784
Create Date: 2026-10-01 14:39:57.769408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e289115dd5b'
down_revision = 'a4fd69e13784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('signup_method', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_created_at'))
        batch_op.drop_column('signup_method')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('landing_event', schema=None) as batch_op:
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###
