"""user achievements

Revision ID: 6e5648d35b11
Revises: 48df2c79e0ac
Create Date: 2026-10-02 11:06:31.454368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5648d35b11'
down_revision = '48df2c79e0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.Column('seen', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_user_achievement')
    )
    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievement_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievement_user_id'))

    op.drop_table('user_achievement')
    # ### end Alembic commands ###
