"""add exercise_favorite table

Revision ID: 70f45d78aeef
Revises: ac1fe86e8814
Create Date: 2026-08-21 16:01:10.212416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f45d78aeef'
down_revision = 'ac1fe86e8814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', name='uq_user_exercise_favorite')
    )
    with op.batch_alter_table('exercise_favorite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_favorite_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_favorite_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_favorite_user_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_favorite_exercise_id'))

    op.drop_table('exercise_favorite')
    # ### end Alembic commands ###
