"""add exercise notes and set type

Revision ID: 7701a8b5b550
Revises: 2c8f9b588337
Create Date: 2026-07-25 12:28:32.519466

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7701a8b5b550"
down_revision = "2c8f9b588337"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exercise", sa.String(length=64), nullable=False),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "exercise", name="uq_user_exercise_note"),
    )
    with op.batch_alter_table("exercise_note", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_exercise_note_exercise"), ["exercise"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_exercise_note_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("set_entry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("set_type", sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("set_entry", schema=None) as batch_op:
        batch_op.drop_column("set_type")

    with op.batch_alter_table("exercise_note", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_exercise_note_user_id"))
        batch_op.drop_index(batch_op.f("ix_exercise_note_exercise"))

    op.drop_table("exercise_note")
    # ### end Alembic commands ###
