"""add ai_analysis

Revision ID: 7faa7fed9150
Revises: 4b1a98fe2152
Create Date: 2026-08-16 19:48:57.329395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7faa7fed9150'
down_revision = '4b1a98fe2152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analysis_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_analysis_user_id'))

    op.drop_table('ai_analysis')
    # ### end Alembic commands ###
