"""add landing_event table

Revision ID: 8172cce81a43
Revises: e18aeeb4379a
Create Date: 2026-08-21 22:29:58.299897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8172cce81a43'
down_revision = 'e18aeeb4379a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('landing_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landing_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_landing_event_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landing_event_timestamp'))
        batch_op.drop_index(batch_op.f('ix_landing_event_event_type'))

    op.drop_table('landing_event')
    # ### end Alembic commands ###
