"""athlete card show progress

Revision ID: 85efa6ac5f5b
Revises: 4f57d3bf9fc9
Create Date: 2026-10-05 14:04:41.211141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85efa6ac5f5b'
down_revision = '4f57d3bf9fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_progress', sa.Boolean(), server_default=sa.true(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('athlete_card', schema=None) as batch_op:
        batch_op.drop_column('show_progress')

    # ### end Alembic commands ###
