"""xp cache and daily checkin

Revision ID: 85f6996e70d9
Revises: 6d559731c646
Create Date: 2026-10-02 17:43:11.040309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f6996e70d9'
down_revision = '6d559731c646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_checkin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('sleep', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('soreness', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_daily_checkin_user_day')
    )
    with op.batch_alter_table('daily_checkin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_checkin_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_checkin_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_seq', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('xp_total', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('xp_cached_seq', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('xp_rules', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('xp_cached_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('xp_level_seen', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('xp_level_seen')
        batch_op.drop_column('xp_cached_at')
        batch_op.drop_column('xp_rules')
        batch_op.drop_column('xp_cached_seq')
        batch_op.drop_column('xp_total')
        batch_op.drop_column('xp_seq')

    with op.batch_alter_table('daily_checkin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_checkin_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_checkin_day'))

    op.drop_table('daily_checkin')
    # ### end Alembic commands ###
