"""add ended_at to workout

Revision ID: 8b5979ae8267
Revises: 0c74af5bce91
Create Date: 2026-08-13 12:33:29.415814

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8b5979ae8267"
down_revision = "0c74af5bce91"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ended_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.drop_column("ended_at")

    # ### end Alembic commands ###
