"""add rest sound/vibration prefs and landing referrer

Revision ID: 915e748fd6da
Revises: dcc1f240fd66
Create Date: 2026-08-27 13:24:03.183862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915e748fd6da'
down_revision = 'dcc1f240fd66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referrer', sa.String(length=255), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rest_sound_enabled', sa.Boolean(), server_default=sa.true(), nullable=False))
        batch_op.add_column(sa.Column('rest_vibration_enabled', sa.Boolean(), server_default=sa.true(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rest_vibration_enabled')
        batch_op.drop_column('rest_sound_enabled')

    with op.batch_alter_table('landing_event', schema=None) as batch_op:
        batch_op.drop_column('referrer')

    # ### end Alembic commands ###
