"""add sex, height_cm, training_goal to user

Revision ID: 923d53e4ff89
Revises: 7faa7fed9150
Create Date: 2026-08-17 19:29:04.944424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923d53e4ff89'
down_revision = '7faa7fed9150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('height_cm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('training_goal', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('training_goal')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
