"""add indexed normalized name columns to exercise catalog

Revision ID: a4fd69e13784
Revises: 97a2ec722805
Create Date: 2026-09-28 21:19:51.819724

"""
import unicodedata

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fd69e13784'
down_revision = '97a2ec722805'
branch_labels = None
depends_on = None


def _strip_accents(s):
    return "".join(
        c for c in unicodedata.normalize("NFKD", s) if not unicodedata.combining(c)
    ).lower()


exercise_table = sa.table(
    'exercise',
    sa.column('id', sa.String),
    sa.column('name', sa.String),
    sa.column('name_es', sa.String),
    sa.column('name_normalized', sa.String),
    sa.column('name_es_normalized', sa.String),
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_normalized', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('name_es_normalized', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_exercise_name_es_normalized'), ['name_es_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_name_normalized'), ['name_normalized'], unique=False)

    # ### end Alembic commands ###

    # Rellena las columnas nuevas para las filas ya existentes del catálogo
    # (800+ en producción) -- sin esto, find_catalog_exercise() no encontraría
    # nada por la columna nueva hasta que cada fila se actualizara por otro
    # motivo (el listener del modelo solo se dispara en insert/update).
    conn = op.get_bind()
    rows = conn.execute(
        sa.select(exercise_table.c.id, exercise_table.c.name, exercise_table.c.name_es)
    ).fetchall()
    for row in rows:
        conn.execute(
            exercise_table.update()
            .where(exercise_table.c.id == row.id)
            .values(
                name_normalized=_strip_accents(row.name),
                name_es_normalized=_strip_accents(row.name_es) if row.name_es else None,
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_name_normalized'))
        batch_op.drop_index(batch_op.f('ix_exercise_name_es_normalized'))
        batch_op.drop_column('name_es_normalized')
        batch_op.drop_column('name_normalized')

    # ### end Alembic commands ###
