"""add secondary_muscles to exercise

Revision ID: ac1fe86e8814
Revises: ace70e2d87f4
Create Date: 2026-08-20 20:53:52.607282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1fe86e8814'
down_revision = 'ace70e2d87f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secondary_muscles', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('secondary_muscles')

    # ### end Alembic commands ###
