"""add google_sub to user for google oauth login

Revision ID: b256c6b23744
Revises: b2e517b98bdf
Create Date: 2026-09-26 14:31:58.736173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b256c6b23744'
down_revision = 'b2e517b98bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_sub', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_google_sub'), ['google_sub'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_google_sub'))
        batch_op.drop_column('google_sub')

    # ### end Alembic commands ###
