"""add performance_note to workout

Revision ID: b45b896c6790
Revises: 09699c271fdd
Create Date: 2026-07-23 19:56:25.562043

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b45b896c6790"
down_revision = "09699c271fdd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("performance_note", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.drop_column("performance_note")

    # ### end Alembic commands ###
