"""landing source tracking

Revision ID: bc5d1f511823
Revises: 6e289115dd5b
Create Date: 2026-10-01 15:12:01.287526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5d1f511823'
down_revision = '6e289115dd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landing_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_landing_event_source'), ['source'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signup_source', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('signup_source')

    with op.batch_alter_table('landing_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landing_event_source'))
        batch_op.drop_column('source')

    # ### end Alembic commands ###
