"""add name_es to exercise

Revision ID: c304899f62c1
Revises: 2c24b08c00cb
Create Date: 2026-08-15 19:37:51.894857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c304899f62c1'
down_revision = '2c24b08c00cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_es', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_exercise_name_es'), ['name_es'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_name_es'))
        batch_op.drop_column('name_es')

    # ### end Alembic commands ###
