"""move effort_scale from workout to user

Revision ID: c54af52f188e
Revises: b45b896c6790
Create Date: 2026-07-24 11:55:10.715955

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "c54af52f188e"
down_revision = "b45b896c6790"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "effort_scale",
                sa.String(length=4),
                nullable=False,
                server_default="rir",
            )
        )

    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.drop_column("effort_scale")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("effort_scale", sa.VARCHAR(length=3), nullable=False)
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("effort_scale")

    # ### end Alembic commands ###
