"""Añade order_index a Routine y rir/rpe a RoutineExercise

Revision ID: e9729bd7ddd2
Revises: 8172cce81a43
Create Date: 2026-08-23 11:47:14.579440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9729bd7ddd2'
down_revision = '8172cce81a43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('order_index', sa.Integer(), nullable=False, server_default=sa.text('0'))
        )

    with op.batch_alter_table('routine_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rir', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rpe', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_exercise', schema=None) as batch_op:
        batch_op.drop_column('rpe')
        batch_op.drop_column('rir')

    with op.batch_alter_table('routine', schema=None) as batch_op:
        batch_op.drop_column('order_index')

    # ### end Alembic commands ###
