"""add body_weight_entry

Revision ID: e9f4eebdde96
Revises: 923d53e4ff89
Create Date: 2026-08-17 19:33:14.756966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f4eebdde96'
down_revision = '923d53e4ff89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_weight_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_weight_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_weight_entry_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_weight_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_weight_entry_user_id'))

    op.drop_table('body_weight_entry')
    # ### end Alembic commands ###
