"""add is_pr to set_entry

Revision ID: f6099b572274
Revises: 1776b45d5e23
Create Date: 2026-08-19 21:26:14.093639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6099b572274'
down_revision = '1776b45d5e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pr', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_entry', schema=None) as batch_op:
        batch_op.drop_column('is_pr')

    # ### end Alembic commands ###
