"""initial models

Revision ID: fa0b34d2e282
Revises:
Create Date: 2026-07-21 14:10:58.557853

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "fa0b34d2e282"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "workout",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=64), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workout_timestamp"), ["timestamp"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_workout_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "set_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exercise", sa.String(length=64), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("reps", sa.Integer(), nullable=False),
        sa.Column("rir", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workout.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("set_entry", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_set_entry_exercise"), ["exercise"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_set_entry_workout_id"), ["workout_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("set_entry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_set_entry_workout_id"))
        batch_op.drop_index(batch_op.f("ix_set_entry_exercise"))

    op.drop_table("set_entry")
    with op.batch_alter_table("workout", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workout_user_id"))
        batch_op.drop_index(batch_op.f("ix_workout_timestamp"))

    op.drop_table("workout")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    # ### end Alembic commands ###
