"""reps warning per user

Revision ID: fd9af15a1a65
Revises: 85efa6ac5f5b
Create Date: 2026-10-08 20:55:55.399102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9af15a1a65'
down_revision = '85efa6ac5f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reps_warning', sa.Integer(), server_default='30', nullable=False))

    # ### end Alembic commands ###

    # Una serie de más de 30 repeticiones ya no tiene 1RM estimado
    # (routes.MAX_1RM_REPS): no puede lucir la medalla de récord. Solo
    # llegaban por importación (la app no dejaba apuntar más de 30).
    # xp: requiere flask recompute-xp (no hace falta: XP_RULES_VERSION subió a 2)
    op.execute(sa.text("UPDATE set_entry SET is_pr = :f WHERE reps > 30 AND is_pr = :t")
               .bindparams(sa.bindparam("f", False), sa.bindparam("t", True)))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reps_warning')

    # ### end Alembic commands ###
